default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASS'] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "educ_test_generator_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "educ_test_generator_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PROD") { "educ_test_generator_production" } %>
  username: <%= ENV['DB_USERNAME_PROD'] %>
  password: <%= ENV['DB_PASS_PROD'] %>
