name: Minitest

env:
  RUBY_VERSION: 3.2.2
  DB_USERNAME: postgres
  DB_PASS: postgres

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.2.2"
    steps:
      - uses: actions/checkout@v3

      - name: Build the stack
        run: docker-compose -f docker-compose.yml up -d

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # 'bundle install' and cache

      - name: Run Database
        run: bundle exec rails db:create db:migrate

      - name: Run runner
        env:
          DBUSER: ${{ env.DB_USERNAME }}
          DBPASS: ${{ env.DB_PASS }}
          RAILS_ENV: test
        run: |
          bundle exec rake --trace
          bundle exec rake report:simplecov

      - name: Coverage Reporter(Only changed)
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage/coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 100
          only_changed_files: true
          show_line: true
          report_name: Only changed files below 100 coverage
          show_missing_max_length: 30

      - name: Coverage Reporter(All Files)
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage/coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 100
          show_line: true
          report_name: All files below 100 coverage
          show_missing_max_length: 30
