name: Minitest

env:
  RUBY_VERSION: 3.2.2
  DB_USERNAME: postgres
  DB_PASS: postgres

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.2.2"
    steps:
      - uses: actions/checkout@v3

      - name: Build the stack
        run: docker-compose -f docker-compose.yml up -d

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # 'bundle install' and cache

      - name: Run Database
        run: bundle exec rails db:create db:migrate

      - name: Run runner
        env:
          DBUSER: ${{ env.DB_USERNAME }}
          DBPASS: ${{ env.DB_PASS }}
          RAILS_ENV: test
        run: bundle exec rake
